# Site settings
title: Francis Windram
email: francis.windram@gmail.com
url: https://fwindram.github.io
description: "Metabolic ecologist, arachnologist, and ecoinformatician."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Francis Windram

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/franciswindram
  - title: github (Personal)
    url: https://github.com/fwindram
  - title: github (Work)
    url: https://github.com/fwimp

# Build settings
markdown: kramdown
permalink: pretty
